release: &release
  blocker: "000000"
  "bugzilla needed": "000000"

release_fine: &release_fine
  fine/yes: "000000"
  fine/no: "000000"
  fine/backported: "000000"
  fine/conflict: "000000"

release_euwe: &release_euwe
  euwe/yes: "555555"
  euwe/no: "555555"
  euwe/backported: "555555"
  euwe/conflict: "555555"

release_darga: &release_darga
  darga/yes: "dddddd"
  darga/no: "dddddd"
  darga/backported: "dddddd"
  darga/conflict: "dddddd"

release_f_plus: &release_f_plus
  <<: *release_fine

release_e_plus: &release_e_plus
  <<: *release_euwe
  <<: *release_f_plus

release_d_plus: &release_d_plus
  <<: *release_darga
  <<: *release_e_plus

common: &common
  bug: "fc2929"
  "bug/sporadic test failure": "fc2929"
  cleanup: "fef2c0"
  developer: "bcf5db"
  documentation: "d4c5f9"
  duplicate: "eeeeee"
  enhancement: "84b6eb"
  hacktoberfest: "ff7619"
  "help wanted": "159818"
  internationalization: "d4c5f9"
  notabug: "eeeeee"
  performance: "e99695"
  question: "cc317c"
  refactoring: "fbca04"
  stale: "eeeeee"
  "technical debt": "eb6420"
  test: "bfe5bf"
  tools: "bcf5db"
  unmergeable: "eeeeee"
  verified: "159818"
  wip: "eeeeee"
  wontfix: "eeeeee"

core_ruby_common: &core_ruby_common
  <<: *common
  dependencies: "6a92bc"

providers_common: &providers_common
  events: "5319e7"
  inventory: "5319e7"
  metrics: "5319e7"
  operations: "5319e7"

ux_common: &ux_common
  ux/review: "cc317c"
  ux/approved: "159818"

gems_common: &gems_common
  <<: *common
  "needs major version": "6a92bc"
  "needs minor version": "6a92bc"

repos:
  manageiq:
    <<: *core_ruby_common
    <<: *release
    <<: *release_d_plus
  manageiq-api:
    <<: *core_ruby_common
    <<: *gems_common
    <<: *release
    <<: *release_f_plus
  manageiq-appliance:
    <<: *common
    <<: *release
    <<: *release_d_plus
  manageiq-appliance-build:
    <<: *common
    <<: *release
    <<: *release_d_plus
  manageiq-automation_engine:
    <<: *core_ruby_common
    <<: *release
    <<: *release_d_plus
  manageiq-consumption:
    <<: *core_ruby_common
    <<: *release
  manageiq-content:
    <<: *core_ruby_common
    <<: *release
    <<: *release_d_plus
  manageiq-gems-pending:
    <<: *core_ruby_common
    <<: *release
    <<: *release_d_plus
  manageiq-pods:
    <<: *common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-amazon:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-ansible_tower:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_f_plus
  manageiq-providers-azure:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-foreman:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_f_plus
  manageiq-providers-google:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_f_plus
  manageiq-providers-hawkular:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-kubernetes:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-lenovo:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_f_plus
  manageiq-providers-nuage:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_f_plus
  manageiq-providers-openshift:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-openstack:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-ovirt:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-providers-scvmm:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_f_plus
  manageiq-providers-vmware:
    <<: *core_ruby_common
    <<: *providers_common
    <<: *release
    <<: *release_d_plus
  manageiq-schema:
    <<: *core_ruby_common
    <<: *release
    <<: *release_f_plus
  manageiq-ui-classic:
    <<: *core_ruby_common
    <<: *ux_common
    <<: *release
    <<: *release_e_plus
  manageiq-ui-service:
    <<: *common
    <<: *ux_common
    <<: *release
    <<: *release_d_plus
  manageiq_docs:
    <<: *release
  manageiq-messaging:
    <<: *common
    <<: *gems_common
  log_decorator:
    <<: *common
    <<: *gems_common
  ui-components:
    <<: *common
    <<: *ux_common
    <<: *gems_common
