release: &release
  blocker: "000000"
  "bugzilla needed": "000000"
  fine/yes: "000000"
  fine/no: "000000"
  fine/backported: "000000"
  fine/conflict: "000000"
  euwe/yes: "555555"
  euwe/no: "555555"
  euwe/backported: "555555"
  euwe/conflict: "555555"
  darga/yes: "dddddd"
  darga/no: "dddddd"
  darga/backported: "dddddd"
  darga/conflict: "dddddd"

common: &common
  bug: "fc2929"
  "bug/sporadic test failure": "fc2929"
  cleanup: "fef2c0"
  developer: "bcf5db"
  documentation: "d4c5f9"
  duplicate: "eeeeee"
  enhancement: "84b6eb"
  "help wanted": "159818"
  internationalization: "d4c5f9"
  notabug: "eeeeee"
  performance: "e99695"
  question: "cc317c"
  refactoring: "fbca04"
  stale: "eeeeee"
  "technical debt": "eb6420"
  test: "bfe5bf"
  tools: "bcf5db"
  unmergeable: "eeeeee"
  verified: "159818"
  wip: "eeeeee"
  wontfix: "eeeeee"

core_ruby_common: &core_ruby_common
  <<: *common
  "gem changes": "6a92bc"

repos:
  manageiq:
    <<: *core_ruby_common
    <<: *release
  manageiq-appliance:
    <<: *common
    <<: *release
  manageiq-appliance-build:
    <<: *common
    <<: *release
  manageiq-content:
    <<: *core_ruby_common
    <<: *release
  manageiq-gems-pending:
    <<: *core_ruby_common
    <<: *release
  manageiq-pods:
    <<: *common
    <<: *release
  manageiq-providers-amazon:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-azure:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-hawkular:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-kubernetes:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-lenovo:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-openshift:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-openstack:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-ovirt:
    <<: *core_ruby_common
    <<: *release
  manageiq-providers-vmware:
    <<: *core_ruby_common
    <<: *release
  manageiq-ui-classic:
    <<: *core_ruby_common
    <<: *release
  manageiq-ui-service:
    <<: *common
    <<: *release
  manageiq_docs:
    <<: *release
