master:
  manageiq:
    has_rake_release: true
  manageiq-appliance:
  manageiq-appliance-build:
  manageiq-content:
    has_rake_release: true
  manageiq-gems-pending:
  manageiq-pods:
  manageiq-providers-amazon:
  manageiq-providers-azure:
  manageiq-providers-lenovo:
  manageiq-providers-vmware:
  manageiq-ui-classic:
  manageiq-ui-service:
  manageiq_docs:
fine:
  manageiq:
    has_rake_release: true
  manageiq-appliance:
  manageiq-appliance-build:
  manageiq-content:
    has_rake_release: true
  manageiq-gems-pending:
  manageiq-pods:
  manageiq-providers-amazon:
  manageiq-providers-azure:
  manageiq-providers-lenovo:
  manageiq-providers-vmware:
  manageiq-ui-classic:
  manageiq-ui-service:
  manageiq_docs:
euwe:
  manageiq:
    has_rake_release: true
  manageiq-appliance:
  manageiq-appliance-build:
  manageiq-pods:
  manageiq-providers-amazon:
  manageiq-ui-service:
  manageiq_docs:
darga:
  manageiq:
    has_rake_release: true
  manageiq-appliance:
  manageiq-appliance-build:
  manageiq-ui-service:
